name = input("Enter Your Name: ")
surname = input("Enter Your Surname: ")
age = input("Enter Your Age: ")
email = input("Enter Your Email: ")
year_of_birth = input("Enter Your Year Of Birth (For Example: 2010): ")
month_and_day_of_birth = input("Enter Your Month And Day Of Birth (For Example: 04.12): ")

print("-----------------------------------------")
print("You have been successfully registered.")
print("Name: " + name + " " + surname)
print("Age: " + age + " " + "years old.")
print("Email: " + email)
print("Birthday: " + year_of_birth + "." + month_and_day_of_birth)